config/routes.rb
Nfproto::Application.routes.draw do

  resources :high_scores

  root :to => "high_scores#index"

end

app/models/high_score.rb
class HighScore < Neo4j::Rails::Model
  property :game, :type => String
  property :score, :type => Fixnum

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery


end

app/controllers/high_scores_controller.rb
class HighScoresController < ApplicationController
  # GET /high_scores
  # GET /high_scores.json
  def index
    @high_scores = HighScore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @high_scores }
    end
  end

  # GET /high_scores/1
  # GET /high_scores/1.json
  def show
    @high_score = HighScore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @high_score }
    end
  end

  # GET /high_scores/new
  # GET /high_scores/new.json
  def new
    @high_score = HighScore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @high_score }
    end
  end

  # GET /high_scores/1/edit
  def edit
    @high_score = HighScore.find(params[:id])
  end

  # POST /high_scores
  # POST /high_scores.json
  def create
    @high_score = HighScore.new(params[:high_score])

    respond_to do |format|
      if @high_score.save
        format.html { redirect_to @high_score, :notice => 'High score was successfully created.' }
        format.json { render :json => @high_score, :status => :created, :location => @high_score }
      else
        format.html { render :action => "new" }
        format.json { render :json => @high_score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /high_scores/1
  # PUT /high_scores/1.json
  def update
    @high_score = HighScore.find(params[:id])

    respond_to do |format|
      if @high_score.update_attributes(params[:high_score])
        format.html { redirect_to @high_score, :notice => 'High score was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @high_score.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /high_scores/1
  # DELETE /high_scores/1.json
  def destroy
    @high_score = HighScore.find(params[:id])
    @high_score.destroy

    respond_to do |format|
      format.html { redirect_to high_scores_url }
      format.json { head :ok }
    end
  end
end

app/helpers/high_scores_helper.rb
module HighScoresHelper
end

app/views/high_scores/_form.html.erb
<%= form_for(@high_score) do |f| %>
  <% if @high_score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@high_score.errors.count, "error") %> prohibited this high_score from being saved:</h2>

      <ul>
      <% @high_score.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game %><br />
    <%= f.text_field :game %>
  </div>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/high_scores/edit.html.erb
<h1>Editing high_score</h1>

<%= render 'form' %>

<%= link_to 'Show', @high_score %> |
<%= link_to 'Back', high_scores_path %>

app/views/high_scores/index.html.erb
<h1>Listing high_scores</h1>

<table>
  <tr>
    <th>Game</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @high_scores.each do |high_score| %>
  <tr>
    <td><%= high_score.game %></td>
    <td><%= high_score.score %></td>
    <td><%= link_to 'Show', high_score %></td>
    <td><%= link_to 'Edit', edit_high_score_path(high_score) %></td>
    <td><%= link_to 'Destroy', high_score, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />
 <%= image_tag "images/logov6-hover.png" %>
<%= link_to 'New High score', new_high_score_path %>

app/views/high_scores/new.html.erb
<h1>New high_score</h1>

<%= render 'form' %>

<%= link_to 'Back', high_scores_path %>

app/views/high_scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Game:</b>
  <%= @high_score.game %>
</p>

<p>
  <b>Score:</b>
  <%= @high_score.score %>
</p>


<%= link_to 'Edit', edit_high_score_path(@high_score) %> |
<%= link_to 'Back', high_scores_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= stylesheet_link_tag "application" %>
    <!--[if lt IE 9]>
	    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <%=  javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
    <%= include_gritter %>
    <script type="text/javascript">
    <!-- Warning Duplicate IDs-->
      $('[id]').each(function(){
        var ids = $('[id='+this.id+']');
        if(ids.length>1 && ids[0]==this)
          console.warn('Multiple IDs #'+this.id);
      });
    </script>
  </head>
  <body>

      <%= yield %>
    </div>
  </body>
</html>